language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

sudo: false

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-dist

script:
    - php vendor/bin/phpunit

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover log/coverage.xml
    - php bin/php-semver-checker-git suggest --allow-detached -vvv --details --include-before=src --include-after=src
